name: flutter_deep_study
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  annotations:
    path: ./lib/code_gen/annotations

dev_dependencies:
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  generator:
    path: ./lib/code_gen/generator
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
